# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d8c74492c9f18c2c5ee35a8bc48f5d5b806b5ac9833abf2f3bb61396840932f19a2e93646ec5e9d621cacf2dc99e4f1966860b6b7b63965bd4c1bc226df7cf

test:
  secret_key_base: cc584682268550bfe388a88733c9710cfcb3982c2445ddb07282f1006b12fdcb408f015945afb7a5457232af9597ae4e52b945c3d7744ba81ea27817c082bba0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
